mariadb_host="172.20.97.202"
mariadb_user="ceres"
mariadb_password="happy365"
mariadb_db="ceres"
mariadb_port="3306"

port="3031"

token_expired_in="60m"
token_maxage=60

token_secret="my-ultra-secure-json-web-token-string"

ansible_ssh_host="172.20.97.203"
ansible_ssh_port="25"
ansible_ssh_user="root"
ansible_ssh_password="Wndchsehd1@345"

ansible_data_path="/data/"